# Create Annotation File

In [0]:
import pandas as pd
from copy import deepcopy

In [0]:
pos = pd.read_csv('Final_Cleaned_YOLO.csv')
neg = pd.read_csv('Final_Neg_Cleaned_YOLO.csv')

In [0]:
pos_totxt = deepcopy(pos)
neg_totxt = deepcopy(neg)

In [15]:
pos_totxt.head()

   Unnamed: 0  Unnamed: 0.1  ... x_max_resized y_max_resized
0           1             1  ...    211.342953    271.390305
1           2             2  ...    396.670950    414.265503
2           4             4  ...    116.491702    197.541637
3           6             6  ...    207.564174    303.672475
4           7             7  ...    215.800000    413.358987

[5 rows x 44 columns]

In [9]:
neg_totxt.head()

   Unnamed: 0  Unnamed: 0.1  ... x_max_resized y_max_resized
0           3             3  ...           0.0           0.0
1          10            10  ...           0.0           0.0
2          13            13  ...           0.0           0.0
3          17            17  ...           0.0           0.0
4          18            18  ...           0.0           0.0

[5 rows x 44 columns]

In [10]:
pos_totxt.columns

Index(['Unnamed: 0', 'Unnamed: 0.1', 'ID', 'DataRow ID', 'Labeled Data',
       'Label', 'Created By', 'Project Name', 'Created At', 'Updated At',
       'Seconds to Label', 'External ID', 'Agreement', 'Benchmark Agreement',
       'Benchmark ID', 'Benchmark Reference ID', 'Dataset Name', 'Reviews',
       'View Label', 'x1', 'y1', 'x2', 'y2', 'x3', 'y3', 'x4', 'y4', 'x_min',
       'y_min', 'x_max', 'y_max', 'class_id', 'x1_resized', 'x2_resized',
       'x3_resized', 'x4_resized', 'y1_resized', 'y2_resized', 'y3_resized',
       'y4_resized', 'x_min_resized', 'y_min_resized', 'x_max_resized',
       'y_max_resized'],
      dtype='object')

In [0]:
pos_totxt.drop(['Unnamed: 0', 'Unnamed: 0.1', 'ID', 'DataRow ID', 'Labeled Data',
       'Label', 'Created By', 'Project Name', 'Created At', 'Updated At',
       'Seconds to Label', 'Agreement', 'Benchmark Agreement',
       'Benchmark ID', 'Benchmark Reference ID', 'Dataset Name', 'Reviews',
       'View Label','x1', 'y1', 'x2', 'y2', 'x3', 'y3', 'x4', 'y4','x_min',
       'y_min', 'x_max', 'y_max','x1_resized', 'x2_resized',
       'x3_resized', 'x4_resized', 'y1_resized', 'y2_resized', 'y3_resized',
       'y4_resized'], axis=1, inplace=True)

In [12]:
pos_totxt.head()

                  External ID  class_id  ...  x_max_resized  y_max_resized
0   2018_VID_1_3_frame373.jpg         1  ...     211.342953     271.390305
1   2018_VID_1_3_frame116.jpg         1  ...     396.670950     414.265503
2  2018_VID_1_3_frame1465.jpg         1  ...     116.491702     197.541637
3   2018_VID_1_3_frame148.jpg         1  ...     207.564174     303.672475
4  2018_VID_1_3_frame1142.jpg         1  ...     215.800000     413.358987

[5 rows x 6 columns]

In [0]:
sed = pd.Series(pos_totxt['class_id'])
pos_totxt.drop('class_id',axis=1, inplace=True)

In [0]:
pos_totxt['class_id'] = sed

In [0]:
pos_totxt.head()

                  External ID  x_min_resized  ...  y_max_resized  class_id
0   2018_VID_1_3_frame373.jpg     107.714420  ...     271.390305         1
1   2018_VID_1_3_frame116.jpg     238.478172  ...     414.265503         1
2  2018_VID_1_3_frame1465.jpg      41.541825  ...     197.541637         1
3   2018_VID_1_3_frame148.jpg     139.586528  ...     303.672475         1
4  2018_VID_1_3_frame1142.jpg      46.800000  ...     413.358987         1

[5 rows x 6 columns]

In [0]:
pos_totxt.to_csv(r'annotation.txt', header=None, index=None, sep=',', mode='a')

In [0]:
def create_annotation_pos(df, name):
    # df['External ID'] = '/content/drive/My Drive/VAUV Dataset/Clipped Images/2018_VID_1_3/' + df['External ID'].astype('str')

    df.drop(['Unnamed: 0', 'Unnamed: 0.1', 'ID', 'DataRow ID', 'Labeled Data',
       'Label', 'Created By', 'Project Name', 'Created At', 'Updated At',
       'Seconds to Label', 'Agreement', 'Benchmark Agreement',
       'Benchmark ID', 'Benchmark Reference ID', 'Dataset Name', 'Reviews',
       'View Label','x1', 'y1', 'x2', 'y2', 'x3', 'y3', 'x4', 'y4','x_min',
       'y_min', 'x_max', 'y_max','x1_resized', 'x2_resized',
       'x3_resized', 'x4_resized', 'y1_resized', 'y2_resized', 'y3_resized',
       'y4_resized'], axis=1, inplace=True)
    
    df['x_min_resized'] = df['x_min_resized'].astype('int')
    df['y_min_resized'] = df['x_min_resized'].astype('int')
    df['x_max_resized'] = df['x_min_resized'].astype('int')
    df['y_max_resized'] = df['x_min_resized'].astype('int')
    
    sed = pd.Series(df['class_id'])
    df.drop('class_id',axis=1, inplace=True)
    df['class_id'] = sed
    df.head()
    df.to_csv(f'{name}.txt', header=None, index=None, sep=',', mode='a')

In [0]:
def create_annotation_neg(df, name):
    # df['External ID'] = '/content/drive/My Drive/VAUV Dataset/Clipped Images/2018_VID_1_3/' + df['External ID'].astype('str')
    df.drop(['Unnamed: 0', 'Unnamed: 0.1', 'ID', 'DataRow ID', 'Labeled Data',
       'Label', 'Created By', 'Project Name', 'Created At', 'Updated At',
       'Seconds to Label', 'Agreement', 'Benchmark Agreement',
       'Benchmark ID', 'Benchmark Reference ID', 'Dataset Name', 'Reviews',
       'View Label','x1', 'y1', 'x2', 'y2', 'x3', 'y3', 'x4', 'y4','x_min',
       'y_min', 'x_max', 'y_max','x1_resized', 'x2_resized',
       'x3_resized', 'x4_resized', 'y1_resized', 'y2_resized', 'y3_resized',
       'y4_resized', 'class_id', 'x_min_resized', 'y_min_resized', 'x_max_resized', 'y_max_resized'], axis=1, inplace=True)
    
    # sed = pd.Series(df['class_id'])
    # df.drop('class_id',axis=1, inplace=True)
    # df['class_id'] = sed
    df.head()
    df.to_csv(f'{name}.txt', header=None, index=None, sep=',', mode='a')

In [0]:
create_annotation_pos(pos_totxt,'annotation_pos')

In [0]:
create_annotation_neg(neg_totxt,'annotation_neg')

In [0]:
! sed 's/,/ /'